#ifndef DEATHLEAK_ENGINE_PLATFORM_PLATFORMDEFINES_H
#define DEATHLEAK_ENGINE_PLATFORM_PLATFORMDEFINES_H

#if !defined(DEATHLEAK_PLATFORM_WINDOWS)
    #define DEATHLEAK_PLATFORM_WINDOWS 0
#endif

#if !defined(DEATHLEAK_PLATFORM_MAC)
    #define DEATHLEAK_PLATFORM_MAC 0
#endif

#if DEATHLEAK_PLATFORM_WINDOWS + DEATHLEAK_PLATFORM_MAC != 1
    #error "Exactly one DEATHLEAK_PLATFORM_* macro must be set to 1."
#endif

#endif
